### ISSUE TITLE
[3338-v12] Fps gets so high that my gpu starts screaming

### ISSUE THREAD

**Issue by Hobey** [AsuMagic/kag-staging#101]
I'm getting 1000+ fps while I'm in the menu and get 700+ fps when in empty ctf servers. The high fps is making my gpu make a high pitch sound (at least I think that is what is happening); the only other program I have experienced this with is Minecraft (when in menu or in game on lowest possible settings and was getting 500+ fps).

The best solution is probably to add a "maximum fps" option so that I can lock it to 300 fps.

**Comment by AsuMagic** [comment]
yeah, it's coil whine. i do want to implement a proper framerate cap partly because of that

**Comment by AsuMagic** [comment]
Will be fixed in 3338-render2d-v2
