### ISSUE TITLE
Capped framerate results in stutters and LAG 2 spam

### ISSUE THREAD

**Issue by bunniewormy** [AsuMagic/kag-staging#153]
roughly every 1.5-2 seconds
```
[23:45:33] <catlover cats>dogs> hi
LAG 2
LAG 2
LAG 2
LAG 2
LAG 2
[23:45:41] <catlover cats>dogs> amogussy
```
doesn't happen in vanilla
doesn't happen with uncapped framerate

**Comment by AsuMagic** [comment]
Reproduces on linux wayland

**Comment by AsuMagic** [comment]
This reproduces despite framerates being very consistent. It may be that the target tick times isn't good enough, or that something else is fucked to make KAG thing it should skip on frames(? if that's what happening).
