### ISSUE TITLE
Sound system crash

### ISSUE THREAD

**Issue by TerminalHash** [asumagic/kag-staging#166]
I'm running it on Artix Linux, SDLMixer version: 2.6.3
```
[18:40:24] Sound engine initialized, using backend SDL2 (dynamic)
[18:40:24] Precaching files...

Thread 8 "SDLAudioP2" received signal SIGILL, Illegal instruction.
```
As I understand it, it's the version of the library (on Ubuntu 18.04 this lib it's very old), or not?

**Comment by asumagic** [comment]
Solved, the cause was SoLoud being compiled with SSE4.1 instructions, which are not supported on these Athlon processors.
