### ISSUE TITLE
Please can you add that when you break bushes you get a little amount wood, for example 10 pieces from one bush?

### ISSUE THREAD

**Issue by NikitaVNsv** [asumagic/kag-staging#171]
Please can you add that when you break bushes you get a little amount wood, for example 10 pieces from one bush?
![image](https://github.com/asumagic/kag-staging/assets/84759709/d8cc71b6-95b6-4aa9-ad65-a2f129e670cd)

**Comment by NikitaVNsv** [comment]
![image](https://github.com/asumagic/kag-staging/assets/84759709/58034d7c-0cbe-4922-96d4-339921fd92f1)

**Comment by asumagic** [comment]
This is not the correct repo for KAG issues. This is the correct one: https://github.com/transhumandesign/kag-base/

**Comment by NikitaVNsv** [comment]
ok
