### ISSUE TITLE
DrawShadowedTextCentered works incorrectly

### ISSUE THREAD

**Issue by NoahTheLegend** [asumagic/kag-staging#191]
the offset of text goes wild

DrawTextCentered
![image](https://github.com/asumagic/kag-staging/assets/76755422/968233ef-d735-45fc-adc4-e276096ac4b1)

DrawShadowedTextCentered
![image](https://github.com/asumagic/kag-staging/assets/76755422/83b58168-71d8-4182-ae85-29e2df8c606f)

**Comment by asumagic** [comment]
Probably fixed next build, vcenter was not applied on some methods
