### ISSUE TITLE
GoldenGuy's "new best kag mod" does not render properly

### ISSUE THREAD

**Issue by AsuMagic** [AsuMagic/kag-staging#38]

**Comment by AsuMagic** [comment]
Possibly related to #20

**Comment by GoldenGuy** [comment]
its caused by my shader

**Comment by AsuMagic** [comment]
Related to #20

**Comment by AsuMagic** [comment]
Should test this again, but it probably would be due to the uniform resolution being passed to the shader. It should read the backtex width rather than the window resolution.

**Comment by AsuMagic** [comment]
u hurt my feelings don't assign screen size uniforms on init
