### ISSUE TITLE
bug with side mouse buttons

### ISSUE THREAD

**Issue by GoldenGuy** [AsuMagic/kag-staging#79]
Function `CControls bool isKeyPressed(int keycode)` doesnt work correctly with KEY_XBUTTON1 and KEY_XBUTTON2 keycodes. when you press/release one of this buttons, the function wont change to true/false until mouse is moved.

**Comment by GoldenGuy** [comment]
its possible that `bool isKeyJustPressed(int keycode)` and `bool isKeyJustReleased(int keycode)` dont work properly too.

**Comment by AsuMagic** [comment]
Will be fixed in 3338-v9, along with support for >2 extra buttons
